name: Tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  javascript_test:
    name: JavaScript Test Action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 18]

    steps:
      - uses: actions/checkout@master

      - name: Setup Node v${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Yarn install
        run: yarn

      - name: Run JavaScript Tests
        run: yarn run test


  ruby_test:
    name: Ruby Test Action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.7, '3.0', 3.1, 3.2]

    steps:
      - uses: actions/checkout@master

      - name: Set up Ruby v${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run ruby tests
        run: bundle exec rake test_ruby
